In [1]:
import numpy as np

- Notes on using external packages

In [5]:
dataset = np.loadtxt("basics_dataset.txt", delimiter=',')

In [6]:
print(dataset)

[[   0.   99.   95.    0.    7.   37.   43.   76.   51.    0.   65.]
 [   1.   33.    8.   18.   95.   50.   54.   41.   47.   32.   65.]
 [   2.   59.   77.    5.   52.   23.   20.   42.   29.    4.    1.]
 [   3.   46.   51.    4.   18.    9.   96.    6.   89.   31.   60.]
 [   4.   57.   30.   56.   55.   51.   69.   39.   19.   81.   18.]
 [   5.   65.   13.    6.   85.   63.   39.   88.   71.   62.   65.]
 [   6.   93.   83.    0.   17.    5.   78.   17.    4.   65.   73.]
 [   7.   23.  100.    5.   85.   54.   50.   72.  100.   47.   17.]
 [   8.   57.   66.   38.   51.   35.   29.   61.   18.   24.   73.]
 [   9.   86.    6.   43.   33.    1.   59.   44.    8.   91.   26.]]


In [7]:
print(type(dataset))

<class 'numpy.ndarray'>


- Notes on the the numpy NDArray object

In [12]:
dataset[0]

array([  0.,  99.,  95.,   0.,   7.,  37.,  43.,  76.,  51.,   0.,  65.])

In [13]:
dataset[0, :]

array([  0.,  99.,  95.,   0.,   7.,  37.,  43.,  76.,  51.,   0.,  65.])

In [14]:
dataset[:, 0]

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [16]:
dataset[-1]

array([  9.,  86.,   6.,  43.,  33.,   1.,  59.,  44.,   8.,  91.,  26.])

In [15]:
dataset[:, -1]

array([ 65.,  65.,   1.,  60.,  18.,  65.,  73.,  17.,  73.,  26.])

- Notes on indexing lists and numpy NDArrays
- Note on advanced indexing

In [20]:
dataset[:, :2]

array([[  0.,  99.],
       [  1.,  33.],
       [  2.,  59.],
       [  3.,  46.],
       [  4.,  57.],
       [  5.,  65.],
       [  6.,  93.],
       [  7.,  23.],
       [  8.,  57.],
       [  9.,  86.]])

In [21]:
dataset[1:4, :]

array([[  1.,  33.,   8.,  18.,  95.,  50.,  54.,  41.,  47.,  32.,  65.],
       [  2.,  59.,  77.,   5.,  52.,  23.,  20.,  42.,  29.,   4.,   1.],
       [  3.,  46.,  51.,   4.,  18.,   9.,  96.,   6.,  89.,  31.,  60.]])